From 13e83e6f60d9ed91316c975425bc4b89c130ec9c Mon Sep 17 00:00:00 2001
From: Leo <thinkabit.ukim@gmail.com>
Date: Fri, 11 Dec 2020 02:08:48 -0300
Subject: [PATCH 2/2] CVE-2020-24584

---
 django/core/cache/backends/filebased.py | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/django/core/cache/backends/filebased.py b/django/core/cache/backends/filebased.py
index 7c2c5c7..88cebef 100644
--- a/django/core/cache/backends/filebased.py
+++ b/django/core/cache/backends/filebased.py
@@ -102,13 +102,18 @@ class FileBasedCache(BaseCache):
 
     def _createdir(self):
         if not os.path.exists(self._dir):
+            # Set the umask because os.makedirs() doesn't apply the "mode" argument
+            # to intermediate-level directories.
+            old_umask = os.umask(0o077)
             try:
                 os.makedirs(self._dir, 0o700)
             except OSError as e:
                 if e.errno != errno.EEXIST:
                     raise EnvironmentError(
                         "Cache directory '%s' does not exist "
                         "and could not be created'" % self._dir)
+            finally:
+                os.umask(old_umask)
 
     def _key_to_file(self, key, version=None):
         """
-- 
2.29.2

